(function(){
const secondary=new Set(["booking","leads","followups","route","services","team","time","mileage","supplies","reports","platform-admin"]);
function calmNavigation(){const nav=document.querySelector(".nav-list");if(!nav||nav.dataset.productPolish==="1")return;nav.dataset.productPolish="1";nav.classList.add("product-nav-calm");nav.querySelectorAll(".nav-item").forEach(btn=>{if(secondary.has(btn.dataset.view))btn.dataset.secondaryNav="true";});nav.querySelectorAll(".nav-section-label").forEach(x=>x.hidden=true);const more=document.createElement("button");more.type="button";more.className="nav-more-toggle";more.setAttribute("aria-expanded","false");more.textContent="More tools  ···";more.addEventListener("click",()=>{const open=nav.classList.toggle("more-open");more.setAttribute("aria-expanded",String(open));more.textContent=open?"Hide tools  ↑":"More tools  ···";});nav.appendChild(more);}
function enrichNotifications(){const list=document.getElementById("notificationList"),bell=document.getElementById("notificationBellBtn"),badge=document.getElementById("notificationBadge");if(!list||list.dataset.productPolish==="1")return;list.dataset.productPolish="1";const decorate=()=>{Array.from(list.children).forEach((item,index)=>{if(!item.dataset.unread)item.dataset.unread=index<3?"true":"false";const t=(item.textContent||"").toLowerCase();item.dataset.priority=/cancel|reschedul|urgent|payment|overdue/.test(t)?"high":"normal";if(item.dataset.productInteractive==="1")return;item.dataset.productInteractive="1";item.setAttribute("tabindex","0");item.addEventListener("click",()=>item.dataset.unread="false");item.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();item.click();}});});};new MutationObserver(()=>{decorate();if(badge&&!badge.hidden){bell?.classList.remove("notification-pulse");requestAnimationFrame(()=>bell?.classList.add("notification-pulse"));}}).observe(list,{childList:true,subtree:true});decorate();}
function bookingControlCenter(){
 const root=document.querySelector('[data-page="booking"]'); if(!root||root.dataset.controlCenter==="1")return; root.dataset.controlCenter="1";
 root.addEventListener("click",e=>{
   const open=e.target.closest("[data-booking-open]"), close=e.target.closest("[data-booking-close]");
   if(open){const key=open.dataset.bookingOpen;root.querySelectorAll("[data-booking-detail]").forEach(x=>x.hidden=x.dataset.bookingDetail!==key);root.querySelector('[data-booking-detail="'+key+'"]')?.scrollIntoView({behavior:"smooth",block:"start"});}
   if(close){const panel=close.closest("[data-booking-detail]");if(panel)panel.hidden=true;root.scrollIntoView({behavior:"smooth",block:"start"});}
 });
}
function install(){calmNavigation();enrichNotifications();bookingControlCenter();}document.addEventListener("DOMContentLoaded",install);window.addEventListener("pageshow",install);const shell=document.getElementById("appShell");if(shell&&"MutationObserver"in window)new MutationObserver(()=>setTimeout(install,0)).observe(shell,{childList:true,subtree:true});install();})();